FROM jenkinsci/jnlp-slave:3.19-1

ARG terraform_version=0.11.7

USER root
RUN wget https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip \
    && whoami && unzip terraform_${terraform_version}_linux_amd64.zip -d /usr/bin/
USER jenkins

RUN terraform version