version: '3'
services:
  jenkins:
    image: scos/jenkins-master
    build: ./master/
    ports:
      - "8080:8080" #jenkins web
      - "50000:50000" #jenkins JNLP slaves
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock